<?php

namespace Smartnode\TalkBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChanRepository extends EntityRepository
{
}
