<?php

namespace Proxies\__CG__\Smartnode\TalkBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Post extends \Smartnode\TalkBundle\Entity\Post implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'postowner', 'postchan', 'creationdate', 'postcontent', 'activated', 'modifidate', 'score');
        }

        return array('__isInitialized__', 'id', 'postowner', 'postchan', 'creationdate', 'postcontent', 'activated', 'modifidate', 'score');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Post $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostowner($postowner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostowner', array($postowner));

        return parent::setPostowner($postowner);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostowner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostowner', array());

        return parent::getPostowner();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostchan($postchan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostchan', array($postchan));

        return parent::setPostchan($postchan);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostchan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostchan', array());

        return parent::getPostchan();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreationdate($creationdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreationdate', array($creationdate));

        return parent::setCreationdate($creationdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreationdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreationdate', array());

        return parent::getCreationdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostcontent($postcontent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostcontent', array($postcontent));

        return parent::setPostcontent($postcontent);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostcontent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostcontent', array());

        return parent::getPostcontent();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivated($activated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivated', array($activated));

        return parent::setActivated($activated);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivated', array());

        return parent::getActivated();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifidate($modifidate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifidate', array($modifidate));

        return parent::setModifidate($modifidate);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifidate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifidate', array());

        return parent::getModifidate();
    }

    /**
     * {@inheritDoc}
     */
    public function setScore($score)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScore', array($score));

        return parent::setScore($score);
    }

    /**
     * {@inheritDoc}
     */
    public function getScore()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScore', array());

        return parent::getScore();
    }

}
