parameters:
#    smartnode_talk.example.class: Smartnode\TalkBundle\Example

services:
#    smartnode_talk.example:
#        class: %smartnode_talk.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
