parameters:
#    smartnodeuser.example.class: Smartnode\userBundle\Example

services:
#    smartnodeuser.example:
#        class: %smartnodeuser.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
